name: Production Android Release

defaults:
  tools:
    bun: "1.4.2"

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Production Android
    type: build
    params:
      platform: android
      profile: production

  submit_android:
    name: Submit Production Android
    type: submit
    needs: [build_android]
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      profile: production
