import { type ComponentType, type FC } from "react";

import {
  IconAlarm,
  IconAlertCircle,
  IconArrowBadgeDown,
  IconArrowBadgeUp,
  IconArrowDown,
  IconArrowsMinimize,
  IconArrowUp,
  IconBalloon,
  IconBarbell,
  IconBedOff,
  IconBike,
  IconBolt,
  IconBulb,
  IconCactus,
  IconChartBubble,
  IconChartRadar,
  IconCheck,
  IconCircleX,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconClock,
  IconCode,
  IconCompass,
  IconCopy,
  IconDots,
  IconDroplet,
  IconDropletHalfFilled,
  IconDropletOff,
  IconEdit,
  IconEgg,
  IconEye,
  IconEyeOff,
  IconExternalLink,
  IconFileExport,
  IconFileImport,
  IconFileText,
  IconFolder,
  IconHammer,
  IconHelpCircle,
  IconIceCream2,
  IconLogout,
  IconMinus,
  IconMoodAngry,
  IconMoodAnnoyed,
  IconMoodCry,
  IconMoodHappy,
  IconMoodNeutral,
  IconMoodSad,
  IconMoodSadSquint,
  IconMoodSick,
  IconPencil,
  IconPillFilled,
  IconPhotoPlus,
  IconPlus,
  IconPoo,
  IconReload,
  IconRepeat,
  IconRipple,
  IconRun,
  IconSearch,
  IconSnowflake,
  IconTools,
  IconToolsKitchen2,
  IconTrash,
  IconTrekking,
  IconUserHeart,
  IconWebhook,
  IconWorld,
  IconBrandFacebook,
  IconBrandInstagram,
  IconBrandReddit,
  IconBrandX,
  IconBrandYoutube,
  IconPlayerPlay,
  IconX,
} from "@tabler/icons-react-native";
import type { IconProps } from "@tabler/icons-react-native";

const icons = {
  alarm: IconAlarm,
  "alert-circle": IconAlertCircle,
  "arrow-badge-down": IconArrowBadgeDown,
  "arrow-badge-up": IconArrowBadgeUp,
  "arrow-down": IconArrowDown,
  "arrow-up": IconArrowUp,
  balloon: IconBalloon,
  barbell: IconBarbell,
  "bed-off": IconBedOff,
  bike: IconBike,
  bolt: IconBolt,
  bulb: IconBulb,
  cactus: IconCactus,
  "chart-bubble": IconChartBubble,
  "chart-radar": IconChartRadar,
  check: IconCheck,
  "circle-x": IconCircleX,
  "chevron-down": IconChevronDown,
  "chevron-left": IconChevronLeft,
  "chevron-right": IconChevronRight,
  "chevron-up": IconChevronUp,
  clock: IconClock,
  code: IconCode,
  compass: IconCompass,
  compact: IconArrowsMinimize,
  copy: IconCopy,
  dots: IconDots,
  droplet: IconDroplet,
  "droplet-half": IconDropletHalfFilled,
  "droplet-off": IconDropletOff,
  edit: IconEdit,
  egg: IconEgg,
  eye: IconEye,
  "eye-off": IconEyeOff,
  "external-link": IconExternalLink,
  file: IconFileText,
  "file-export": IconFileExport,
  "file-import": IconFileImport,
  folder: IconFolder,
  hammer: IconHammer,
  "help-circle": IconHelpCircle,
  "ice-cream-2": IconIceCream2,
  logout: IconLogout,
  minus: IconMinus,
  "mood-angry": IconMoodAngry,
  "mood-annoyed": IconMoodAnnoyed,
  "mood-cry": IconMoodCry,
  "mood-happy": IconMoodHappy,
  "mood-neutral": IconMoodNeutral,
  "mood-sad": IconMoodSad,
  "mood-sad-squint": IconMoodSadSquint,
  "mood-sick": IconMoodSick,
  pencil: IconPencil,
  pill: IconPillFilled,
  "photo-plus": IconPhotoPlus,
  plus: IconPlus,
  poo: IconPoo,
  reload: IconReload,
  repeat: IconRepeat,
  ripple: IconRipple,
  run: IconRun,
  search: IconSearch,
  snowflake: IconSnowflake,
  tools: IconTools,
  "tools-kitchen-2": IconToolsKitchen2,
  trash: IconTrash,
  trekking: IconTrekking,
  "user-heart": IconUserHeart,
  webhook: IconWebhook,
  world: IconWorld,
  "brand-facebook": IconBrandFacebook,
  "brand-instagram": IconBrandInstagram,
  "brand-reddit": IconBrandReddit,
  "brand-x": IconBrandX,
  "brand-youtube": IconBrandYoutube,
  "player-play": IconPlayerPlay,
  x: IconX,
} satisfies Record<string, ComponentType<IconProps>>;

export type IconName = keyof typeof icons;

interface AppIconProps extends IconProps {
  name: IconName;
  filled?: boolean;
}

export const Icon: FC<AppIconProps> = (props) => {
  const { name, filled = false, strokeWidth, ...iconProps } = props;
  const Component = icons[name];

  return (
    <Component
      {...iconProps}
      fill={filled ? iconProps.color : "transparent"}
      strokeWidth={filled ? 0 : (strokeWidth ?? 1.8)}
    />
  );
};
